source "http://rubygems.org"

gem "rake", "0.9.2.2"
gem "coyote", "1.2.0"
gem "sinatra", :require => "sinatra/base"
gem "i18n"
gem "active_support"
gem "rspec"
gem "growl"
gem "listen", "0.4.7"
gem "guard", "1.2.3"
